input: './assets/samplesheet_local.csv'
outdir: './out_test_local/'
genome: 'GATK.GRCh38'
intervals: './intervals.bed'
tools: 'haplotypecaller,snpeff'
joint_germline: true
igenomes_base: './data/ref/'
snpeff_cache: './data/ref/snpeff_cache/'
vep_cache: './data/ref/vep_cache/'
snpeff_genome: 'GRCh38'
snpeff_db: '105'
vep_species: 'homo_sapiens'
vep_genome: 'GRCh38'
vep_cache_version: '110'
ngscheckmate_bed: '/home/rodtheo/Bioinfo/project-data/nextflow/sarek/data/ref/Homo_sapiens/GATK/GRCh38/Annotation/NGSCheckMate/SNP_GRCh38_hg38_wChr.bed'
